import { Inter, Bitter } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar/Sidebar";
import TopBar from "./topbar/TopBar";


const inter = Inter({ subsets: ["latin"] });
const bitter = Bitter({ weight: ['200', '300', '400', '500', '600', '700'], subsets: ["latin"], variable: '--bitter' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${bitter.variable}`}>
        <div className="flex">
          <Sidebar />
          <div style={{ width: `calc(100% - 300px)` }} className="h-screen">
            <TopBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
